version: '3'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python project/manage.py makemigrations 
      && python project/manage.py migrate
      && python project/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "quizdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  postgres_data:
